name: Run E2E tests

on:
  push:
    branches:
      - trunk
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - trunk
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    if: "${{ ( github.event_name == 'pull_request' ) || github.event_name == 'push' }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ['@general', '@forms', '@settings']
    
    env:
      WP_ADMIN_USERNAME: ${{ secrets.WP_ADMIN_USERNAME }}
      WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}
      JOBBER_API_KEY: ${{ secrets.JOBBER_API_KEY }}
      JOBBER_CLIENT_ID: ${{ secrets.JOBBER_CLIENT_ID }}
      JOBBER_CLIENT_SECRET: ${{ secrets.JOBBER_CLIENT_SECRET }}

    permissions:
      pull-requests: write

    name: E2E tests (${{ matrix.type }})
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
      
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      
      - name: Install Node dependencies
        run: npm ci && npm run build
      
      - name: Install playwright
        run: npx playwright install --with-deps chromium
      
      - name: Setup E2E environment
        run: npm run env:start
      
      - name: Run E2E tests
        id: jobber_e2e_tests
        if: ${{ github.event_name == 'pull_request' && matrix.type != '@general' }}
        run: npm run test:e2e -- --grep ${{ matrix.type }}
      
      - name: Run E2E tests (General)
        id: jobber_e2e_tests_general
        if: ${{ github.event_name == 'pull_request' && matrix.type == '@general' }}
        run: npm run test:e2e -- --grep-invert "@forms|@settings"
      
      - name: Remove existing labels
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            const labelsToRemove = ['status: e2e tests passing', 'status: e2e tests failing'];
            const { data } = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            if ( data.length == 0 ) {
              console.log ( 'Issue has no labels; not attempting to remove any labels' );
              return;
            }
            for ( const labelName of labelsToRemove ) {
              const labelExists = data.filter( label => label.name === labelName );
              if ( labelExists.length > 0 ) {
                console.log( `Removing label "${labelName}"...` );
                await github.rest.issues.removeLabel({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: labelName
                })
              }
            }
      
      - name: Update Success Label
        if: |
          always() &&
          ( steps.jobber_e2e_tests.conclusion == 'success' || steps.jobber_e2e_tests_general.conclusion == 'success' )
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['status: e2e tests passing']
            })
      
      - name: Update Failure Label
        if: |
          always() &&
          ( steps.jobber_e2e_tests.conclusion == 'failure' || steps.jobber_e2e_tests_general.conclusion == 'failure' )
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['status: e2e tests failing']
            })
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.type }}
          path: tests/e2e/test-results/report
          retention-days: 2
          if-no-files-found: ignore
